apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-${ENV}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: ${ENV}
  template:
    metadata:
      labels:
        app: myapp
        version: ${ENV}
    spec:
      containers:
      - name: myapp
        image: ${IMAGE}
        ports:
        - containerPort: 5000

